export const data = [
  {
    name: 'fwc',
    items: ['stadiums', 'museum'],
  },
  {
    name: 'a',
    items: ['qat', 'ecu', 'sen', 'ned'],
  },
  {
    name: 'b',
    items: ['eng', 'irn', 'usa', 'wal'],
  },
  {
    name: 'c',
    items: ['arg', 'ksa', 'mex', 'pol'],
  },
  {
    name: 'd',
    items: ['fra', 'aus', 'den', 'tun'],
  },
  {
    name: 'e',
    items: ['esp', 'crc', 'ger', 'jpn'],
  },
  {
    name: 'f',
    items: ['bel', 'can', 'mar', 'cro'],
  },
  {
    name: 'g',
    items: ['bra', 'srb', 'sui', 'cmr'],
  },
  {
    name: 'h',
    items: ['por', 'gha', 'uru', 'kor'],
  },
  {
    name: 'special',
    items: ['fwc'],
  },
]

export const countries = [
  'qatar',
  'ecuador',
  'senegal',
  'netherlands',
  'england',
  'iran',
  'usa',
  'wales',
  'argentina',
  'saudi-arabia',
  'mexico',
  'poland',
  'france',
  'australia',
  'denmark',
  'tunisia',
  'spain',
  'costa-rica',
  'germany',
  'japan',
  'belgium',
  'canada',
  'morocco',
  'croatia',
  'brazil',
  'serbia',
  'switzerland',
  'cameroon',
  'portugal',
  'ghana',
  'uruguay',
  'south-korea',
]

export const countriesObj = {
  qat: 'qatar',
  ecu: 'ecuador',
  sen: 'senegal',
  ned: 'netherlands',
  eng: 'england',
  irn: 'iran',
  usa: 'usa',
  wal: 'wales',
  arg: 'argentina',
  ksa: 'saudi-arabia',
  mex: 'mexico',
  pol: 'poland',
  fra: 'france',
  aus: 'australia',
  den: 'denmark',
  tun: 'tunisia',
  esp: 'spain',
  crc: 'costa-rica',
  ger: 'germany',
  jpn: 'japan',
  bel: 'belgium',
  can: 'canada',
  mar: 'morocco',
  cro: 'croatia',
  bra: 'brazil',
  srb: 'serbia',
  sui: 'switzerland',
  cmr: 'cameroon',
  por: 'portugal',
  gha: 'ghana',
  uru: 'uruguay',
  kor: 'south-korea',
}
